import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import categories from "@/data/categories";
import { AppProvider } from "@/context/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  return (
    <html lang="en">
     
      <body className={inter.className}>
        <AppProvider bok ={"bok"}>
        
      

        <Header ></Header>
      
       
        {children}
        
        </AppProvider>
        </body>
    </html>
  );
}
